### ISSUE TITLE
Rails 4.2 support

### ISSUE THREAD

**Issue by neoecos** [batdevis/swagger_engine#1]
Hi, 

I've been trying to use this, but i was able to get gem install it, i'm using rails 4.2+

**Comment by batdevis** [comment]
Hi @neoecos , I just pushed the gem in rubygems.org.
If you want you can retry.

**Comment by neoecos** [comment]
@batdevis Thanks, I'll be trying again the next week.

**Comment by dazza-codes** [comment]
Is this still an open issue?  What is the issue, exactly?

**Comment by batdevis** [comment]
No, I can close this.
